# https://mlflow.org

mlflow:
  _target_: pytorch_lightning.loggers.mlflow.MLFlowLogger
  experiment_name: "${paths.output_dir}/mlflow"
  # run_name: ""
  # tracking_uri: ${paths.output_dir}/mlflow/mlruns # run `mlflow ui` command inside the `logs/mlflow/` dir to open the UI
  tags: null
  save_dir: "${paths.output_dir}/mlflow"
  prefix: ""
  artifact_location: "${paths.output_dir}/mlflow/artifacts"
  # run_id: ""
